name: Extract Phone Data
on:
  workflow_dispatch: # Manual trigger

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Install Osmium
        run: |
          sudo apt-get update
          sudo apt-get install -y osmium-tool

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm install axios

      - name: Run Extraction Script
        run: node test-osm-filter.js

      - name: Upload Results
        uses: actions/upload-artifact@v6
        with:
          name: phone-tagged-osm-files
          path: "*-phones.osm"
          retention-days: 5